name: Documentation

# on:
#   schedule:
#     - cron: '0 0 */1 * *'

on:
  push:
    branches:
      - add-actions

jobs:
  update-docs:
     name: update-docs
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: build
         run: |
          git log --pretty=format:"%s" | head -n 1 > commit
          docker image build .github/docs -t docs
          mkdir ready
          docker run --rm -v `pwd`:/drive docs
       - name: lookup
         run: |
           ls -l ready
           chown -R runner:docker ready/man1
           ls -l ready

#       - name: push
#         run: .github/docs/push.sh  ${{ secrets.GITHUB_TOKEN }}
