name: Documentation

# on:
#   schedule:
#     - cron: '0 0 */1 * *'
# TODO

on:
  push:
    branches:
      - add-actions

jobs:
  update-docs:
     name: update-docs
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - name: build
         uses: ./.github/docs
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
