name: Documentation

# on:
#   schedule:
#     - cron: '* 1 * * *'

on:
  push:
    branches:
      - add-actions

jobs:
  update-docs:
     name: update-docs
     runs-on: self-hosted
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: lookaround
         run: ls -l
       - name: building
         run: |
          docker image build .github/docs -t docs
          docker run --rm docs ${{ secrets.GITHUB_TOKEN }}
          docker image rm docs