name: Documentation

# on:
#   schedule:
#     - cron: '0 0 */1 * *'

on:
  push:
    branches:
      - add-actions

jobs:
  update-docs:
     name: update-docs
     runs-on: self-hosted
     steps:
       - name: checkout
         uses: actions/checkout@v2
       # - name: build
       #   run: |
       #    docker image build .github/docs -t docs
       #    docker run --rm -v `pwd`:/drive docs
       - name: lookaround
         run: |
#          git log --pretty=format:"%s" | head -n 1
          ls -la
       - name: building
         run: .github/docs/update.sh
          docker image build .github/docs -t docs
          docker run --rm docs ${{ secrets.GITHUB_TOKEN }}
          docker image rm docs