name: Documentation

# on:
#   schedule:
#     - cron: '0 0 */1 * *'
# TODO 

on:
  push:
    branches:
      - add-actions

jobs:
  update-docs:
     name: update-docs
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: build
         run: |
          git log --pretty=format:"%s" | head -n 1 > commit
          docker image build .github/docs -t docs
          mkdir ready
          docker run -v `pwd`:/drive --name mycontainer docs
          docker -ps -a
          docker cp    mycontainer:/home/opam/bap.upstream/doc/man1 ready/
          docker cp    mycontainer:/home/opam/bap.upstream/doc/man3 ready/
          docker cp -L mycontainer:/home/opam/bap.upstream/doc/odoc ready/
       - name: lookup
         run:  ls -l ready
#       - name: push
#         run: .github/docs/push.sh  ${{ secrets.GITHUB_TOKEN }}
