name: Documentation

# on:
#   schedule:
#     - cron: '0 0 */1 * *'
# TODO

on:
  push:
    branches:
      - add-actions

jobs:
  update-docs:
     name: update-docs
     runs-on: ubuntu-latest
     steps:
       - name: build
         uses: gitoleg/my-actions/documentation@master
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: check
         run: |
           ls -la
           ls -la lisp/